package core

const (
	UnitName           = "UnitName"
	LocId              = "LocId"
	Speed              = "Speed"
	EventTime          = "EventTime"
	TimeStamp          = "TimeStamp"
	Latitude           = "Latitude"
	Longitude          = "Longitude"
	OdometerMi         = "OdometerMi"
	OdometerKm         = "OdometerKm"
	Switches           = "Switches"
	Reason             = "Reason"
	Heading            = "Heading"
	Ignition           = "Ignition"
	Relay              = "Relay"
	Satellites         = "Satellites"
	RSSI               = "RSSI"
	CSID               = "CSID"
	IBID               = "IBID"
	FMI                = "FMI"
	Supply             = "Supply"
	GPSStat            = "GPSStat"
	TemperatureSensors = "TemperatureSensors"
	FuelLevel          = "FuelLevel"
	RawData            = "RawData"
)
